### ISSUE TITLE
Modifier la réponse CSV

### ISSUE THREAD

**Issue by pierrejego** [LETG/coastlinetracking#10]
La réponse actuellement contient un format spécifique qui n'est pas lisible tel quel par les outils JS de graphique.

Il faudra revoir ce fonctionnement

**Comment by pierrejego** [comment]
Le contenu de la réponse évolue en fonction du nombre de traits de côte sélectionné, chaque groupe de valeur étant délimité par un |

Ici le cas avec  4 traits de cote

```
1952-06-10|2000-06-15|2012-11-11|2021-07-05
rad|separe;cumule;taux|separe;cumule;taux|separe;cumule;taux
R2|none;none;none|0.019900894550185483;0.019900894550185483;4.391194737463699E-6|1.2439298454192105;1.263830739969396;3.9402275749737424E-4
R3|0.7244994262872488;0.7244994262872488;4.131497640780388E-5|0.05604195696693924;0.7805413832541881;1.2365833399589417E-5|0.7498159777792417;1.5303573610334298;2.375090205192403E-4
R4|4.5746981551583366;4.5746981551583366;2.608746666947044E-4|0.3038683056541207;4.878566460812458;6.704949374539292E-5|-0.6102262408684356;4.2683402199440215;-1.9329307597986555E-4
R5|3.939661034759757;3.939661034759757;2.246613272559168E-4|0.9298856628185191;4.869546697578276;2.051821850879345E-4|-0.5741867881469523;4.2953599094313235;-1.8187734816184744E-4
R6|3.2022103950693728;3.2022103950693728;1.826078008137188E-4|0.6665112105600387;3.8687216056294114;1.4706778697264755E-4|-1.1418873191428034;2.726834286486608;-3.617001327661715E-4
R7|2.4936340341741015;2.4936340341741015;1.4220084592689905E-4|-0.5393562030503524;1.9542778311237492;-1.1901063615409364E-4|-1.9892302309695693;-0.034952399845820104;-6.301014352136741E-4
R8|2.1025398603510683;2.1025398603510683;1.1989848656199067E-4|0.051063889997438085;2.1536037503485064;1.126740732511873E-5|-2.108993862277105;0.044609888071401205;-6.680373336322792E-4
R9|2.8297057323856256;2.8297057323856256;1.6136551849826788E-4|-3.6160447773692925;-0.7863390449836669;-7.978916101873991E-4|-2.731401412261252;-3.517740457244919;-8.651889174093292E-4
R10|2.4643540950598966;2.4643540950598966;1.4053114136974775E-4|-2.2374112593746855;0.226942835685211;-4.936918048046526E-4|-3.4563414395276593;-3.2293986038424483;-0.001094818321041387
R11|3.3195268176981854;3.3195268176981854;1.8929783403844578E-4|-3.80472129228043;-0.4851944745822445;-8.39523674377853E-4|-2.3908444474812183;-2.876038922063463;-7.57315314374792E-4
R12|2.205473303473618;2.205473303473618;1.2576832250647913E-4|-3.707550566018757;-1.5020772625451393;-8.180826491656569E-4|-4.367571155139474;-5.869648417684613;-0.0013834561783780403
```

Pourquoi avoir les valeurs separe, cumule et taux alors que le graphique ne semble afficher que le separe ?

**Comment by pierrejego** [comment]
Est-il possible dans notre cas de modifier le service WPS pour avoir en résultat un json ne contenant que les informations separe pour chacune des dates  ?
L'idée c'est de limiter la complexité de parsing côte application mviewer en standardisant la réponse.

Je ne vois pas de structure  csv qui nous permettrait d'avoir simplement les informations.

Mais nous pourrions avoir un json
```
{"result": [ 
{"tdc":"2000-06-15", "data":[ICI un tableau de toutes valeurs dans l'ordre de chaque R]},
{"tdc":"2012-11-11", "data":[ICI un tableau de toutes valeurs dans l'ordre de chaque R]},
{"tdc":"22021-07-05", "data":[ICI un tableau de toutes valeurs dans l'ordre de chaque R]},
]}
```

Nous pourrions même garder les valeurs cumule et taux si celles ci doivent être affichées

**Comment by mrouan** [comment]
Oui c'est possible, le json me semble en effet plus moderne et adapté à de la visu web en js. il faut conserver les valeurs cumulé et le taux de recul dans la structure de données et afficher séparé et cumulé. on verra plus tard pour l'affichage du taux car Serge se pose la question de comment il est calculé (diff entre 2 dates puis ramené à l'année ? On a pas de doc la dessus. Si tu peux analyser le code pour nous dire comment il est calculé. Merci Envoyé depuis mon appareil Galaxy
-------- Message d'origine --------De : Pierre ***@***.***> Date : 03/05/2022  23:12  (GMT+01:00) À : LETG/coastlinetracking ***@***.***> Cc : mrouan ***@***.***>, Assign ***@***.***> Objet : Re: [LETG/coastlinetracking] Modifier la réponse CSV (Issue #10) 

Est-il possible dans notre cas de modifier le service WPS pour avoir en résultat un json ne contenant que les informations separe pour chacune des dates  ?

L'idée c'est de limiter la complexité de parsing côte application mviewer en standardisant la réponse.

Je ne vois pas de structure  csv qui nous permettrait d'avoir simplement les informations.

Mais nous pourrions avoir un json

{"result": [ 

{"tdc":"2000-06-15", "data":[ICI un tableau de toutes valeurs dans l'ordre de chaque R]},

{"tdc":"2012-11-11", "data":[ICI un tableau de toutes valeurs dans l'ordre de chaque R]},

{"tdc":"22021-07-05", "data":[ICI un tableau de toutes valeurs dans l'ordre de chaque R]},

]}



Nous pourrions même garder les valeurs cumule et taux si celles ci doivent être affichées

**Comment by mrouan** [comment]
Car le maddog actuel en smalltalk ne les calcul pas. C'est une évolution ajouté lors du développement des WPSEnvoyé depuis mon appareil Galaxy
-------- Message d'origine --------De : Pierre ***@***.***> Date : 03/05/2022  23:00  (GMT+01:00) À : LETG/coastlinetracking ***@***.***> Cc : Subscribed ***@***.***> Objet : Re: [LETG/coastlinetracking] Modifier la réponse CSV (Issue #10) 

Le contenu de la réponse évolue en fonction du nombre de traits de côte sélectionné, chaque groupe de valeur étant délimité par un |

Ici le cas avec  4 traits de cote

1952-06-10|2000-06-15|2012-11-11|2021-07-05

rad|separe;cumule;taux|separe;cumule;taux|separe;cumule;taux

R2|none;none;none|0.019900894550185483;0.019900894550185483;4.391194737463699E-6|1.2439298454192105;1.263830739969396;3.9402275749737424E-4

R3|0.7244994262872488;0.7244994262872488;4.131497640780388E-5|0.05604195696693924;0.7805413832541881;1.2365833399589417E-5|0.7498159777792417;1.5303573610334298;2.375090205192403E-4

R4|4.5746981551583366;4.5746981551583366;2.608746666947044E-4|0.3038683056541207;4.878566460812458;6.704949374539292E-5|-0.6102262408684356;4.2683402199440215;-1.9329307597986555E-4

R5|3.939661034759757;3.939661034759757;2.246613272559168E-4|0.9298856628185191;4.869546697578276;2.051821850879345E-4|-0.5741867881469523;4.2953599094313235;-1.8187734816184744E-4

R6|3.2022103950693728;3.2022103950693728;1.826078008137188E-4|0.6665112105600387;3.8687216056294114;1.4706778697264755E-4|-1.1418873191428034;2.726834286486608;-3.617001327661715E-4

R7|2.4936340341741015;2.4936340341741015;1.4220084592689905E-4|-0.5393562030503524;1.9542778311237492;-1.1901063615409364E-4|-1.9892302309695693;-0.034952399845820104;-6.301014352136741E-4

R8|2.1025398603510683;2.1025398603510683;1.1989848656199067E-4|0.051063889997438085;2.1536037503485064;1.126740732511873E-5|-2.108993862277105;0.044609888071401205;-6.680373336322792E-4

R9|2.8297057323856256;2.8297057323856256;1.6136551849826788E-4|-3.6160447773692925;-0.7863390449836669;-7.978916101873991E-4|-2.731401412261252;-3.517740457244919;-8.651889174093292E-4

R10|2.4643540950598966;2.4643540950598966;1.4053114136974775E-4|-2.2374112593746855;0.226942835685211;-4.936918048046526E-4|-3.4563414395276593;-3.2293986038424483;-0.001094818321041387

R11|3.3195268176981854;3.3195268176981854;1.8929783403844578E-4|-3.80472129228043;-0.4851944745822445;-8.39523674377853E-4|-2.3908444474812183;-2.876038922063463;-7.57315314374792E-4

R12|2.205473303473618;2.205473303473618;1.2576832250647913E-4|-3.707550566018757;-1.5020772625451393;-8.180826491656569E-4|-4.367571155139474;-5.869648417684613;-0.0013834561783780403

Pourquoi avoir les valeurs separe, cumule et taux alors que le graphique ne semble afficher que le separe ?

**Comment by pierrejego** [comment]
Passage en Json et maintien du CSV
