### ISSUE TITLE
wrong orientation for the calculation of radials

### ISSUE THREAD

**Issue by mrouan** [LETG/coastlinetracking#12]
Depending on the orientation of the reference line sections, the radials are not calculated on the same side.
![Capture](https://user-images.githubusercontent.com/5336907/176184885-9bd25670-0699-445a-a007-7e5fb76db97a.PNG)

**Comment by mrouan** [comment]
Une solution pourrait consister à tracer les radiales des 2 côtés et d'abandonner le choix de l'orientation.

**Comment by Gaetanbrl** [comment]
le calcule initiale semble retourner des résultats surprenants.

Il existe dans GeoTools un algorithme qui permet de : 

- Récupérer une distance entre 2 points
- Calculer l'angle entre 2 points
- Ajouter un point B à partir d'un point A selon un angle et une distance

https://docs.geotools.org/stable/userguide/library/referencing/calculator.html

Ce sont les 2 dernières fonctionnalités qui peuvent nous aider à tracer les radiales selon cette logique : 

![image](https://github.com/LETG/coastlinetracking/assets/16317988/af1e4eb1-3ad9-4eee-9fdc-c86a59805615)

Sur ce schéma, nous partons de la ligne de référence dessinée de A vers B.

Au préalable, nous calculons le nombre de points à rajouter selon la distance entre les radiales et la distance totale de la ligne de référence (une division simple). Si la ligne est de 200m et qu'on souhaite une distance de 50m entre chaque radiale, nous aurons alors 4 radiales à rajouter.

Sur cette ligne, nous ajoutons alors un point C entre A et B, selon une distance définie par un paramètre 1 du calcule du WPS. Puis on dessine une radiale de distance définie par le paramètre 2 du WPS. Le dessin de cette radiale doit respecter un angle de 90° si la valeur du paramètre 3 du WPS est TRUE ou angle de 270° (voir -90°) si la valeur du paramètre est à false.

Les angles à 90° ou 270° permettent de respecter ce principe : 

![image](https://github.com/LETG/coastlinetracking/assets/16317988/86403ca3-8cb7-49eb-bead-a2b8bac44e18)

On part ensuite du point suivant et ainsi de suite selon le nombre de radiale à rajouter (une boucle).

**Comment by Gaetanbrl** [comment]
@mrouan je suis en train de tester un algo de calcul des radiales qui me donne des résultats. J'ai besoin d'un retour de ta part sur ces résultats donc.

Sur ces captures : 
- en noir type antenne les radiales selon l'algo actuellement utilisé
- en Jaune les radiales que j'ai calculée avec un algo spécifiqué
- Les étiquettes sont celles des radiales en jaune

![image](https://github.com/LETG/coastlinetracking/assets/16317988/6e16fa71-31f8-4717-9e0c-306b80ef425f)

![image](https://github.com/LETG/coastlinetracking/assets/16317988/686fda09-3afc-4e91-8c18-9e4df8fa6e6a)

![image](https://github.com/LETG/coastlinetracking/assets/16317988/82e7fe4e-0b91-4bec-abe3-e6744b9fd366)


## cas particuliers

1. Radiales non carrées

On voit que la radiale 3 et 18 n'est pas "droite" et ne forme pas un angle droit avec la ligne de référence.
C'est dû au calcule des segments (calcul initial non modifié) qui prend la pente entre le 1er et le dernier point lorsqu'un segment est composé de plusieurs segment (multi-ligne).

![image](https://github.com/LETG/coastlinetracking/assets/16317988/a76eb8cb-255e-4cce-bc64-f20585b00e7f)
![image](https://github.com/LETG/coastlinetracking/assets/16317988/7dd4a570-2899-47c0-a865-49a1bc33c284)
![image](https://github.com/LETG/coastlinetracking/assets/16317988/cb70916e-0eb5-4b81-b1cf-13a43ed592b7)


3. radiales à la fin et pas au début

![image](https://github.com/LETG/coastlinetracking/assets/16317988/08202d34-4a7b-43e0-b907-dc8ff65d6d59)

**Comment by mrouan** [comment]
Pour le sens des radiales c'est ok en revanche il est important que :
- la radiale forme un angle droit avec le segment, il faut donc calculer la pente à partir du dernier segment et non d'un segment artificiel entre le 1er et dernier point.
- il faut afficher la première radiale qui doit être au début du premier segment et ne pas mettre la dernière sur l'extrémité du dernier segment.

**Comment by Gaetanbrl** [comment]
Merci c'est noté @mrouan.
Il me reste également à valider / finaliser le calcul du sens inverse.

**Comment by Gaetanbrl** [comment]
@mrouan voici les résultats suite aux dernières modifications.
Les radiales semblent bien dans le bon sens hormis celles qui sont sur la pente entre le premier et le dernier point dans le cas de sous-segments. Ce cas sera corrigé d'ici ce midi.

C'est testable ici :

https://gis.jdev.fr/mviewer/?config=apps/maddog.xml

![image](https://github.com/LETG/coastlinetracking/assets/16317988/e495a283-9348-429a-b609-9aa532dbbf47)

![image](https://github.com/LETG/coastlinetracking/assets/16317988/d3c253cf-41ce-4552-a862-cb4e71bd16bc)

**Comment by Gaetanbrl** [comment]
@mrouan je viens de pousser le correctif sur notre fork contenant la correction suivante : 

- Utilisation du dernier sous-segment pour le calcule de la radiale

Je te laisse tester sur notre mviewer et commenter ici les résultats de tes tests (ok / ko) pour : 

- le calcule de l'orientation de la radiale
- le calcule de la radiale en cas de sous-segment 

https://gis.jdev.fr/mviewer/?config=apps/maddog.xml

**Comment by Gaetanbrl** [comment]
A corriger : 

- [ ] placer la première radiale sur le premier point du premier sous segment si le premier segment est divisé en n segments
