### ISSUE TITLE
TDC - Corriger le taux de recul annuel

### ISSUE THREAD

**Issue by Gaetanbrl** [LETG/coastlinetracking#20]
# Description

La méthode actuelle du calcule du taux de recul (en mètres / an) est basé sur la méthodologie décrite ci-dessous.

Mais cette méthode n'affiche jamais un taux de recule négatif puisqu'elle se base sur une distance de segment positive entre 2 dates données le long d'une radiale.

> Pour rappel, la méthode de calcule des radiale et des distances a été détaillée ici : https://github.com/LETG/coastlinetracking/issues/14

## Explication de la méthode actuelle 

En prenant 3 dates le long d'une radiale : 

- 07/06/2005 - point 0
- 30/05/2009 - point A
- 01/07/2022 - point B

![image](https://github.com/LETG/coastlinetracking/assets/16317988/88a97280-f96d-4b5f-a05d-f7283a6d1990)

Les étapes suivantes sont appliquées :

1. Calcule de la distance entre 2 point (on exclu point 0 de référence) : point A -> point B

2. Calcule du nombre de jours entre les deux dates du point A et B

3. Application de la formule du taux de recul :  

**taux = (separateDistance / nbrJours) * 365**

4. Affichage en graphique

## Méthode envisagée

Contrairement à la méthode précédente, il est souhaité de pouvoir affiché une valeur négative ou positive du taux d'évolution du trait de côte entre plusieurs date.

* **Cas du taux négatif**

Le taux devra être négatif dans le cas où point B recule par rapport au point A et que la distance entre point 0 et point B est supérieure à la distance point 0 et point A.

Cela signifie que le trait de côte avance vers la terre et s'écarte de la mer.

![image](https://github.com/LETG/coastlinetracking/assets/16317988/056b8183-c691-4760-9e32-d46295d2181a)

* **Cas du taux positif**

Le taux devra être positif dans le cas où point B avance par rapport au point A et que la distance entre point 0 et point B est inférieure à la distance point 0 et point A.

Cela signifie que le trait de côte avance vers la mer.

![image](https://github.com/LETG/coastlinetracking/assets/16317988/de16299c-84ee-40bc-887e-0a6c46a4e7a5)

**@mrouan est-ce que cette méthode convient ?**

**Comment by mrouan** [comment]
@Gaetanbrl oui c'est bien cela

**Comment by Gaetanbrl** [comment]
Aussi, on avait une question en suspend, est-ce que vous souhaitez afficher le taux annuel moyen entre deux dates ou le taux d'évolution global de la distance entre 2 dates ?

**Comment by mrouan** [comment]
nous souhaitons afficher le taux annuel entre 2 dates en m/an

**Comment by Gaetanbrl** [comment]
Je viens de modifier le signe de l'évolution actuellement calculée permettant d'avoir le nombre de mètres / an entre 2 dates selon une avancée ou un recule du trait.

Déjà le graph est plus parlant sur VOUGO entre 11/06/1952 et 14/08/1978 : 

https://gis.jdev.fr/mviewer/?config=apps/maddog.xml#

![image](https://github.com/LETG/coastlinetracking/assets/16317988/cad55cc3-de89-410e-9bb3-fb6375291623)
On voit qu'à partir de la radiale 13, le TDC a un taux de recule positif (vers la terre).

Cela représente donc bien une courbe de l'évolution de la distance moyenne par an pour une distance totale entre 2 dates. 
Je trouve toutefois que la notion de taux d'évolution indiquée dans les labels est trompeuse car pour moi le taux d'évolution représente le % d'évolution d'une valeur entre deux dates (calcul différent).

J'ai donc également rajouté dans le retour du WPS le taux global d'évolution entre 2 dates et le taux d'évolution annuel qui permet de savoir entre 2 dates, quelle est le % d'évolution appliqué chaque année  en partant de la ligne de référence (comme indiqué dans la présentation de l'issue).

Si le taux est négatif, on revient vers la ligne de référence le long de la radiale (c'est une avancé - le recule est négatif). Si le taux est positif, on s'écarte de la ligne de référence le long de la radiale et on va vers la terre (c'est un recule).

```
% d'évolution par an :
- Vd : Valeur de départ -> distance entre ref line et année la plus ancienne
- Va : Valeur d'arrivée -> distance entre ref line et année la plus récente
- x : % d'évolution appliqué chaque année
Si Vd * (1+x)^n = Va,
Alors x = ((Va/Vd)^1/n)-1
```

**Comment by Gaetanbrl** [comment]
> J'ai donc également rajouté dans le retour du WPS le taux global d'évolution entre 2 dates et le taux d'évolution annuel

Vu avec Mathias, ces valeurs peuvent être intéressantes mais risquent d'être illisibles dans un graphique avec plusieurs traits de côtes. 

Sur le premier taux d'évolution (graphique initial), il est demandé : 
- D'inverser le signe (un taux de recul est négatif quand le trait recule vers la terre) -> Fait dans le dernier commit au-dessus
- De modifier le label "taux de recule" par "taux d'évolution"
